// tb_gkp_decoder_cosim.sv
//
// Bit-for-bit co-simulation harness for gkp_decoder.v.
// Reads vectors generated by scripts/generate_gkp_cosim_vectors.py.
//
// Run through scripts/run_gkp_cosim.py.

`timescale 1ns/1ps

module tb_gkp_decoder_cosim;

    localparam int ADC_WIDTH   = 16;
    localparam int SCALE_WIDTH = 32;
    localparam int MAX_WAIT    = 80;

    logic clk = 1'b0;
    logic rst_n = 1'b0;

    always #5 clk = ~clk;

    logic signed [ADC_WIDTH-1:0] adc_in;
    logic valid_in;
    logic signed [SCALE_WIDTH-1:0] inv_delta_q;
    logic signed [SCALE_WIDTH-1:0] delta_adc_q;
    logic signed [31:0] coeffs [0:3];
    logic [15:0] alpha;

    logic valid_out;
    logic signed [ADC_WIDTH-1:0] adc_corr;
    logic [1:0] syndrome;

    gkp_decoder #(
        .ADC_WIDTH(ADC_WIDTH),
        .SCALE_WIDTH(SCALE_WIDTH)
    ) dut (
        .clk(clk),
        .rst_n(rst_n),
        .adc_in(adc_in),
        .valid_in(valid_in),
        .inv_delta_q(inv_delta_q),
        .delta_adc_q(delta_adc_q),
        .coeffs(coeffs),
        .alpha(alpha),
        .valid_out(valid_out),
        .adc_corr(adc_corr),
        .syndrome(syndrome)
    );

    string vector_path;
    integer fd;
    integer rc;
    integer line_no;
    integer pass_count;
    integer fail_count;
    integer wait_count;
    reg [1023:0] skip_line;

    logic [15:0] adc_hex;
    logic [31:0] inv_hex;
    logic [31:0] delta_hex;
    logic [31:0] c0_hex;
    logic [31:0] c1_hex;
    logic [31:0] c2_hex;
    logic [31:0] c3_hex;
    logic [15:0] alpha_hex;
    logic [15:0] expected_corr_hex;
    logic [3:0]  expected_syn_hex;

    task automatic drive_one_vector;
        begin
            @(posedge clk);
            adc_in      <= adc_hex;
            inv_delta_q <= inv_hex;
            delta_adc_q <= delta_hex;
            coeffs[0]   <= c0_hex;
            coeffs[1]   <= c1_hex;
            coeffs[2]   <= c2_hex;
            coeffs[3]   <= c3_hex;
            alpha       <= alpha_hex;
            valid_in    <= 1'b1;

            @(posedge clk);
            valid_in    <= 1'b0;

            wait_count = 0;
            while (!valid_out && wait_count < MAX_WAIT) begin
                @(posedge clk);
                wait_count++;
            end

            if (!valid_out) begin
                $display("FAIL line %0d: timeout waiting for valid_out", line_no);
                fail_count++;
            end else begin
                if ((adc_corr !== expected_corr_hex) || (syndrome !== expected_syn_hex[1:0])) begin
                    $display("FAIL line %0d: adc=%h expected_corr=%h got_corr=%h expected_syn=%h got_syn=%h",
                             line_no, adc_hex, expected_corr_hex, adc_corr, expected_syn_hex[1:0], syndrome);
                    fail_count++;
                end else begin
                    pass_count++;
                end
            end
        end
    endtask

    initial begin
        adc_in = '0;
        valid_in = 1'b0;
        inv_delta_q = '0;
        delta_adc_q = '0;
        coeffs[0] = '0;
        coeffs[1] = '0;
        coeffs[2] = '0;
        coeffs[3] = '0;
        alpha = '0;
        line_no = 0;
        pass_count = 0;
        fail_count = 0;

        if (!$value$plusargs("VECTORS=%s", vector_path)) begin
            vector_path = "sim/gkp_cosim_vectors.hex";
        end

        fd = $fopen(vector_path, "r");
        if (fd == 0) begin
            $display("ERROR: could not open vector file: %s", vector_path);
            $finish(2);
        end

        repeat (5) @(posedge clk);
        rst_n = 1'b1;
        repeat (5) @(posedge clk);

        while (!$feof(fd)) begin
            rc = $fscanf(fd, "%h %h %h %h %h %h %h %h %h %h\n",
                         adc_hex, inv_hex, delta_hex, c0_hex, c1_hex, c2_hex, c3_hex,
                         alpha_hex, expected_corr_hex, expected_syn_hex);
            if (rc == 10) begin
                line_no++;
                drive_one_vector();
                repeat (4) @(posedge clk);
            end else begin
                // Consume comments/blank lines.
                void'($fgets(skip_line, fd));
            end
        end

        $fclose(fd);

        $display("COSIM SUMMARY: pass=%0d fail=%0d", pass_count, fail_count);
        if (fail_count != 0) begin
            $finish(1);
        end
        $finish(0);
    end

endmodule
